// src/lib/missions.js

export const missions = [
  // ------------------ PAST MISSIONS ------------------
  {
    id: 1,
    name: "Apollo 11",
    agency: "NASA",
    destination: "Moon",
    status: "Completed",
    launchDate: "1969-07-16",
    crew: 3,
    duration: "8 days",
    cost: "$25B",
    thumbnail: "https://www.nasa.gov/sites/default/files/thumbnails/image/apollo11.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 2,
    name: "Apollo 12",
    agency: "NASA",
    destination: "Moon",
    status: "Completed",
    launchDate: "1969-11-14",
    crew: 3,
    duration: "10 days",
    cost: "$25B",
    thumbnail: "https://www.nasa.gov/sites/default/files/thumbnails/image/apollo12.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 3,
    name: "Challenger STS-6",
    agency: "NASA",
    destination: "Low Earth Orbit",
    status: "Completed",
    launchDate: "1983-04-04",
    crew: 4,
    duration: "5 days",
    cost: "$450M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Challenger_launch.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 4,
    name: "Hubble Space Telescope Launch",
    agency: "NASA",
    destination: "Low Earth Orbit",
    status: "Completed",
    launchDate: "1990-04-24",
    crew: 5,
    duration: "15 days",
    cost: "$4.7B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Hubble_Space_Telescope_in_orbit.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 5,
    name: "ISS Assembly Mission 1",
    agency: "NASA/Roscosmos",
    destination: "ISS",
    status: "Completed",
    launchDate: "1998-11-20",
    crew: 6,
    duration: "30 days",
    cost: "$150B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/d/d9/ISS_assembly.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 6,
    name: "Mars Pathfinder",
    agency: "NASA",
    destination: "Mars",
    status: "Completed",
    launchDate: "1996-12-04",
    crew: 0,
    duration: "85 days",
    cost: "$280M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/7/73/Mars_Pathfinder.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 7,
    name: "Cassini-Huygens",
    agency: "NASA/ESA",
    destination: "Saturn",
    status: "Completed",
    launchDate: "1997-10-15",
    crew: 0,
    duration: "19 years",
    cost: "$3.26B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Cassini-Huygens.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 8,
    name: "Chandrayaan-1",
    agency: "ISRO",
    destination: "Moon",
    status: "Completed",
    launchDate: "2008-10-22",
    crew: 0,
    duration: "312 days",
    cost: "$54M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/6/60/Chandrayaan-1.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/en/8/89/ISRO_Logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 9,
    name: "Curiosity Rover",
    agency: "NASA",
    destination: "Mars",
    status: "Completed",
    launchDate: "2011-11-26",
    crew: 0,
    duration: "Ongoing since landing",
    cost: "$2.5B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/2/29/PIA17043_-_A_Portrait_of_Curiosity.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 10,
    name: "Juno Mission",
    agency: "NASA",
    destination: "Jupiter",
    status: "Completed",
    launchDate: "2011-08-05",
    crew: 0,
    duration: "5 years (arrival), extended mission ongoing",
    cost: "$1.1B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Juno_-_NASA_spacecraft.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },

  // ------------------ ONGOING MISSIONS ------------------
  {
    id: 11,
    name: "Chandrayaan-3",
    agency: "ISRO",
    destination: "Moon",
    status: "Ongoing",
    launchDate: "2023-07-14",
    crew: 0,
    duration: "Ongoing",
    cost: "$75M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Chandrayaan-3.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/en/8/89/ISRO_Logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 12,
    name: "Artemis I",
    agency: "NASA",
    destination: "Moon",
    status: "Ongoing",
    launchDate: "2024-11-16",
    crew: 0,
    duration: "25 days",
    cost: "$4.1B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/5/57/Artemis_I.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 13,
    name: "SpaceX Crew-7",
    agency: "SpaceX/NASA",
    destination: "ISS",
    status: "Ongoing",
    launchDate: "2025-04-26",
    crew: 4,
    duration: "180 days",
    cost: "$55M per seat",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/6/68/SpaceX_Crew-7.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/d/d3/SpaceX-Logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 14,
    name: "James Webb Space Telescope",
    agency: "NASA/ESA/CSA",
    destination: "L2 Orbit",
    status: "Ongoing",
    launchDate: "2021-12-25",
    crew: 0,
    duration: "Ongoing",
    cost: "$10B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/4/4f/JWST_-_James_Webb_Space_Telescope.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 15,
    name: "Tianwen-1",
    agency: "CNSA",
    destination: "Mars",
    status: "Ongoing",
    launchDate: "2020-07-23",
    crew: 0,
    duration: "Ongoing",
    cost: "$8.4B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/7/74/Tianwen-1.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/5/5b/CNSA_logo.png",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },

  // ------------------ UPCOMING MISSIONS ------------------
  {
    id: 16,
    name: "Artemis II",
    agency: "NASA",
    destination: "Moon",
    status: "Upcoming",
    launchDate: "2025-11-01",
    crew: 4,
    duration: "10 days",
    cost: "$4.1B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/5/57/Artemis_program_logo.png",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 17,
    name: "Lunar Gateway Module 1",
    agency: "NASA/ESA",
    destination: "Lunar Orbit",
    status: "Upcoming",
    launchDate: "2026-03-15",
    crew: 0,
    duration: "Ongoing",
    cost: "$10B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/4/49/Lunar_Gateway.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 18,
    name: "Mars Sample Return",
    agency: "NASA/ESA",
    destination: "Mars",
    status: "Upcoming",
    launchDate: "2026-09-20",
    crew: 0,
    duration: "Ongoing",
    cost: "$7B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/1/18/Mars_Sample_Return.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 19,
    name: "Chandrayaan-4",
    agency: "ISRO",
    destination: "Moon",
    status: "Upcoming",
    launchDate: "2026-12-10",
    crew: 0,
    duration: "Ongoing",
    cost: "$90M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Chandrayaan.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/en/8/89/ISRO_Logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 20,
    name: "Artemis III",
    agency: "NASA",
    destination: "Moon",
    status: "Upcoming",
    launchDate: "2027-05-14",
    crew: 4,
    duration: "15 days",
    cost: "$5B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/5/57/Artemis_program_logo.png",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },

  // TODO: Add missions 21-50 (SpaceX Starship, Blue Origin, JAXA missions, Roscosmos Luna, ESA ExoMars, etc.)
  // Continue from id: 20

  {
    id: 21,
    name: "Starship Orbital Flight Test",
    agency: "SpaceX",
    destination: "Low Earth Orbit",
    status: "Ongoing",
    launchDate: "2023-04-20",
    crew: 0,
    duration: "2 hours",
    cost: "$2B (development)",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Starship_SN15.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/d/d3/SpaceX-Logo.svg",
    quickStats: { launches: 2, successes: 0, failures: 2 },
  },
  {
    id: 22,
    name: "Starship Crew Lunar Mission",
    agency: "SpaceX",
    destination: "Moon",
    status: "Upcoming",
    launchDate: "2027-09-10",
    crew: 10,
    duration: "7 days",
    cost: "$5B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/f/f4/SpaceX_Starship_Render.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/d/d3/SpaceX-Logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 23,
    name: "New Glenn Maiden Flight",
    agency: "Blue Origin",
    destination: "Low Earth Orbit",
    status: "Upcoming",
    launchDate: "2026-01-15",
    crew: 0,
    duration: "3 hours",
    cost: "$2.5B (development)",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/1/1e/New_Glenn.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Blue_Origin_logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 24,
    name: "New Shepard Tourism Flights",
    agency: "Blue Origin",
    destination: "Suborbital",
    status: "Ongoing",
    launchDate: "2021-07-20",
    crew: 6,
    duration: "11 minutes",
    cost: "$250k per seat",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/f/fb/New_Shepard_Launch.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Blue_Origin_logo.svg",
    quickStats: { launches: 20, successes: 19, failures: 1 },
  },
  {
    id: 25,
    name: "Hayabusa2",
    agency: "JAXA",
    destination: "Asteroid Ryugu",
    status: "Completed",
    launchDate: "2014-12-03",
    crew: 0,
    duration: "6 years",
    cost: "$150M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Hayabusa2.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/5/54/JAXA_logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 26,
    name: "Hayabusa3",
    agency: "JAXA",
    destination: "Asteroid 1998 KY26",
    status: "Upcoming",
    launchDate: "2031-01-01",
    crew: 0,
    duration: "5 years",
    cost: "$200M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/1/14/Hayabusa_render.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/5/54/JAXA_logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 27,
    name: "Luna 25",
    agency: "Roscosmos",
    destination: "Moon",
    status: "Failed",
    launchDate: "2023-08-10",
    crew: 0,
    duration: "11 days",
    cost: "$200M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/9/96/Luna_25.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Roscosmos_logo.png",
    quickStats: { launches: 1, successes: 0, failures: 1 },
  },
  {
    id: 28,
    name: "Luna 26",
    agency: "Roscosmos",
    destination: "Moon",
    status: "Upcoming",
    launchDate: "2027-06-01",
    crew: 0,
    duration: "Ongoing",
    cost: "$250M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Luna_26_concept.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Roscosmos_logo.png",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 29,
    name: "ExoMars Rover Rosalind Franklin",
    agency: "ESA/Roscosmos",
    destination: "Mars",
    status: "Upcoming",
    launchDate: "2028-09-20",
    crew: 0,
    duration: "2 years",
    cost: "$1.3B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/2/23/ExoMars_Rover.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/3/3e/ESA_logo.png",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 30,
    name: "JUICE Mission",
    agency: "ESA",
    destination: "Jupiter",
    status: "Ongoing",
    launchDate: "2023-04-14",
    crew: 0,
    duration: "12 years",
    cost: "$1.5B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/1/18/JUICE_spacecraft.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/3/3e/ESA_logo.png",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 31,
    name: "BepiColombo",
    agency: "ESA/JAXA",
    destination: "Mercury",
    status: "Ongoing",
    launchDate: "2018-10-20",
    crew: 0,
    duration: "7 years",
    cost: "$2B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/7/77/BepiColombo_spacecraft.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/3/3e/ESA_logo.png",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 32,
    name: "Tiangong Space Station",
    agency: "CNSA",
    destination: "Low Earth Orbit",
    status: "Ongoing",
    launchDate: "2021-04-29",
    crew: 6,
    duration: "10+ years",
    cost: "$8B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Tiangong_space_station.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/5/5b/CNSA_logo.png",
    quickStats: { launches: 5, successes: 5, failures: 0 },
  },
  {
    id: 33,
    name: "Shenzhou 16",
    agency: "CNSA",
    destination: "Tiangong",
    status: "Ongoing",
    launchDate: "2023-05-30",
    crew: 3,
    duration: "180 days",
    cost: "$400M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/5/50/Shenzhou_16.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/5/5b/CNSA_logo.png",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 34,
    name: "Shenzhou 17",
    agency: "CNSA",
    destination: "Tiangong",
    status: "Ongoing",
    launchDate: "2024-10-26",
    crew: 3,
    duration: "180 days",
    cost: "$400M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/3/37/Shenzhou_17.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/5/5b/CNSA_logo.png",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 35,
    name: "Polaris Dawn",
    agency: "SpaceX",
    destination: "Low Earth Orbit",
    status: "Upcoming",
    launchDate: "2025-06-01",
    crew: 4,
    duration: "5 days",
    cost: "$200M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Polaris_Dawn.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/d/d3/SpaceX-Logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 36,
    name: "Axiom Space AX-3",
    agency: "Axiom Space/SpaceX",
    destination: "ISS",
    status: "Ongoing",
    launchDate: "2024-01-18",
    crew: 4,
    duration: "14 days",
    cost: "$55M per seat",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Axiom_AX-3.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Axiom_Space_logo.png",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 37,
    name: "Axiom Space AX-4",
    agency: "Axiom Space/SpaceX",
    destination: "ISS",
    status: "Upcoming",
    launchDate: "2025-12-05",
    crew: 4,
    duration: "14 days",
    cost: "$55M per seat",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Axiom_AX-4.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Axiom_Space_logo.png",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 38,
    name: "ISRO Gaganyaan 1",
    agency: "ISRO",
    destination: "Low Earth Orbit",
    status: "Upcoming",
    launchDate: "2025-08-15",
    crew: 3,
    duration: "7 days",
    cost: "$1.5B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/4/45/Gaganyaan.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/en/8/89/ISRO_Logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 39,
    name: "ISRO Aditya-L1",
    agency: "ISRO",
    destination: "Sun (L1 Orbit)",
    status: "Ongoing",
    launchDate: "2023-09-02",
    crew: 0,
    duration: "5 years",
    cost: "$46M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Aditya-L1.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/en/8/89/ISRO_Logo.svg",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 40,
    name: "ISRO Shukrayaan",
    agency: "ISRO",
    destination: "Venus",
    status: "Upcoming",
    launchDate: "2031-01-01",
    crew: 0,
    duration: "5 years",
    cost: "$500M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Shukrayaan.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/en/8/89/ISRO_Logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 41,
    name: "Europa Clipper",
    agency: "NASA",
    destination: "Europa (Jupiter)",
    status: "Upcoming",
    launchDate: "2026-10-10",
    crew: 0,
    duration: "6 years",
    cost: "$4.25B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/4/49/Europa_Clipper.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 42,
    name: "Dragonfly Mission",
    agency: "NASA",
    destination: "Titan (Saturn)",
    status: "Upcoming",
    launchDate: "2028-06-30",
    crew: 0,
    duration: "9 years",
    cost: "$1B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/8/83/Dragonfly_Mission.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 43,
    name: "Nancy Grace Roman Telescope",
    agency: "NASA",
    destination: "Space Telescope (L2)",
    status: "Upcoming",
    launchDate: "2027-05-01",
    crew: 0,
    duration: "10 years",
    cost: "$3.2B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Nancy_Grace_Roman_Telescope.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 44,
    name: "Hera Mission",
    agency: "ESA",
    destination: "Asteroid Dimorphos",
    status: "Upcoming",
    launchDate: "2024-10-01",
    crew: 0,
    duration: "6 years",
    cost: "$320M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/2/27/Hera_mission.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/3/3e/ESA_logo.png",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 45,
    name: "Astroscale ELSA-d",
    agency: "Astroscale (Japan)",
    destination: "Low Earth Orbit",
    status: "Ongoing",
    launchDate: "2021-03-22",
    crew: 0,
    duration: "2 years",
    cost: "$100M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/6/67/Astroscale_ELSA-d.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/d/d6/Astroscale_logo.png",
    quickStats: { launches: 1, successes: 1, failures: 0 },
  },
  {
    id: 46,
    name: "Rocket Lab Photon Lunar",
    agency: "Rocket Lab",
    destination: "Moon Orbit",
    status: "Upcoming",
    launchDate: "2026-02-01",
    crew: 0,
    duration: "1 year",
    cost: "$200M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/5/55/Rocket_Lab_Photon.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Rocket_Lab_logo.png",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 47,
    name: "Virgin Galactic Unity Flights",
    agency: "Virgin Galactic",
    destination: "Suborbital",
    status: "Ongoing",
    launchDate: "2021-07-11",
    crew: 6,
    duration: "1 hour",
    cost: "$450k per seat",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Virgin_Galactic_Unity.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Virgin_Galactic_logo.png",
    quickStats: { launches: 10, successes: 9, failures: 1 },
  },
  {
    id: 48,
    name: "OneWeb Satellite Constellation",
    agency: "OneWeb",
    destination: "Low Earth Orbit",
    status: "Ongoing",
    launchDate: "2019-02-27",
    crew: 0,
    duration: "10 years",
    cost: "$3B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/9/9a/OneWeb_Satellite.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/f/f7/OneWeb_logo.png",
    quickStats: { launches: 15, successes: 14, failures: 1 },
  },
  {
    id: 49,
    name: "Amazon Project Kuiper",
    agency: "Amazon",
    destination: "Low Earth Orbit",
    status: "Upcoming",
    launchDate: "2025-12-01",
    crew: 0,
    duration: "15 years",
    cost: "$10B",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Project_Kuiper.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
  {
    id: 50,
    name: "NASA Mars Ice Mapper",
    agency: "NASA/JAXA",
    destination: "Mars",
    status: "Upcoming",
    launchDate: "2030-07-01",
    crew: 0,
    duration: "5 years",
    cost: "$800M",
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Mars_Ice_Mapper.jpg",
    agencyLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    quickStats: { launches: 0, successes: 0, failures: 0 },
  },
];
